version: '3.8'

services:
  embed-carousel:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=file:./prisma/dev.db
    volumes:
      # Volume para persistir banco de dados SQLite
      - embed_db:/app/server/prisma
      # Volume para persistir uploads
      - embed_uploads:/app/server/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/health', (r) => process.exit(r.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  embed_db:
    driver: local
  embed_uploads:
    driver: local 